### ISSUE TITLE
Cache data and a big log file present

### ISSUE THREAD

**Issue by mensfeld** [sixoverground/tang#30]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for OSS libraries using Diffend.io.

While reviewing the changes for this lib, I noticed, that:
- the cache directory is being included in the release
- spec/tang_app/log/test.log is included in the release

Names of dirs and files that imho should not be in the final release:

- `spec/tang_app/tmp`
- `spec/tang_app/log`

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

Removing those two mentioned, shaves 70MB if space when using this lib.

If the presence of cache data is valid I would love the reasoning. Thanks!

**Comment by craigphares** [comment]
Actual log files and cache files are not present in this codebase. The directories you refer to are intentionally kept, but no actual logs or temporary files are committed to the repo. The directories are empty.

**Comment by mensfeld** [comment]
@craigphares I may have not been clear enough: https://rubygems.org/gems/tang/versions/0.2.1 - this release is 21MB big (0.2.1)

**Comment by craigphares** [comment]
@mensfeld oh wow! That should _not_ be the case. Let me see why those are getting pushed with the gem.

**Comment by mensfeld** [comment]
I know it should not be ;) that's why I reported :heart:

**Comment by craigphares** [comment]
Removed the spec directory altogether from the actual gem release. Thanks for bringing this up @mensfeld !

**Comment by mensfeld** [comment]
Anytime. Will keep an eye on that for the upcoming releases ;)
